Repository Qihoo360/XSQL, pull requests merged in 2019-09, with the labels that each got.

#5 [CORE] Fix com.fasterxml.jackson.core:jackson-databind vulnerabilities.
  pom.xml
Labels: security

#8 [CORE] Fix org.jpmml:pmml-model vulnerabilities.
  pom.xml
Labels: security

#14 [DOCS] Correct address of release page of REAMDME.md
  README.md
Labels: documentation

#15 [CORE] Drop all redundant *.iml
  assembly/spark-assembly_2.11.iml
  spark-parent_2.11.iml
  sql/catalyst/spark-catalyst_2.11.iml
  sql/core/spark-sql_2.11.iml
  sql/hive/spark-hive_2.11.iml
  sql/xsql-druid/spark-xsql-druid_2.11.iml
  sql/xsql-hbase/spark-xsql-hbase_2.11.iml
  sql/xsql-monitor/spark-xsql-monitor_2.11.iml
  sql/xsql-shell/spark-xsql-shell.iml
  sql/xsql/spark-xsql_2.11.iml
Labels: bug

#17 [DOCS] Upload logo and update docs.
  README-CN.md
  README.md
  sql/xsql/docs/docs/images/XSQL-300200.png
  sql/xsql/docs/docs/index.md
Labels: documentation

#23 [DOCS] Fix mistake in getting started.
  sql/xsql/docs/docs/getting_started/Getting_Started.md
Labels: documentation

#33 [CORE] Fix puppycrawl vulnerabilities
  pom.xml
Labels: security

#40 [SHELL] Fix xsql shell vulnerabilities
  sql/xsql-shell/pom.xml
Labels: security

#39 [DOCS] Add kafka version compatibility and other info into docs.
  sql/xsql/docs/docs/images/kafka.png
  sql/xsql/docs/docs/index.md
Labels: documentation
